### ISSUE TITLE
Module package error

### ISSUE THREAD

**Issue by rbizzell40** [victorsteven/Go-JWT-Postgres-Mysql-Restful-API#6]
Hello Victor nice work with your code. When I try to pull down the package in main.go I get this error

 Repository not found.
fatal: repository 'https://github.com/victorsteven/fullstack/' not found
package github.com/victorsteven/fullstack/api: exit status 128

**Comment by victorsteven** [comment]
Hi Rodney, 

This is because the name used on the go modules does not match the repository name on Github. Rather pull:
https://github.com/victorsteven/Go-JWT-Postgres-Mysql-Restful-API

**Comment by rbizzell40** [comment]
Ok thanks brother appreciate it

**Comment by rbizzell40** [comment]
Hello Question in your main.go you have thispackage main

import (
	"github.com/victorsteven/fullstack/api"
)

func main() {

	api.Run()

}


But this import isn't correct. I want to understand if that import needs to be changed to https://github.com/victorsteven/Go-JWT-Postgres-Mysql-Restful-API

**Comment by rbizzell40** [comment]
Resolved issue
